src/accounts/urls.py
from django.conf.urls import url, include
from django.urls import path

from . import views
from . import views_admin

app_name = 'accounts'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('password-change', views.PasswordChangeView.as_view(),
        name='password-change'),
    path('password-reset', views.PasswordResetView.as_view(),
        name='password-reset'),
    path('password-reset-done', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    path('users', views_admin.moderate_users, name='users'),
    path('delete_user', views_admin.delete_user, name='delete_user'),
]

src/apps/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'apps'

urlpatterns = [
	# This URL can be used to make use of SearchFilterForm and filter 
	# search results based on User inputs. Refer forms.py and uncomment this when required.
    # path('tag/', views.tagSearch, name='tagSearch'),
    path('<slug:name>/', views.appPage, name='appPage'),
    path('tag/all/', views.tagSearch, name='allApps'),
    path('tag/<slug:name>/', views.tagSearch, name='tagSearch'),
    path('feedback/<int:num>/', views.feedback, name='feedback'),
]

src/profiles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('myapps', views.userLanding, name='user_landing'),
    path('me', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/search/urls.py
from django.conf.urls import include, url
from django.urls import path


from . import views

app_name = 'search'

urlpatterns = [
    #url(r'^$', include('haystack.urls')),
    path('', views.search, name='searchpage')
]

src/templates/_brandname.html
App Store

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="{% get_static_prefix %}common/lib/bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% get_static_prefix %}common/lib/js/jquery.cookie.js"></script>

  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}common/lib/bootstrap/css/bootstrap.min.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}common/css/base.css"/>

  {% block more_head %}{% endblock %}

  <title>ns-3 App Store {% block title %}{% endblock %}</title>

  {# Google Analytics Snippet #}
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-155159-10']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  {# End of Google Analytics Snippet #}
</head>

<body style="padding-top: 0;">
  {# Navigation bar #}
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-inner">
      <div class="container">
        <a href="/"><img src="{% get_static_prefix %}common/img/logo.png"></a>
        <ul class="nav pull-right">
          <li>
            <form action="{% url 'search:searchpage' %}" method="get" class="navbar-search pull-right">
              <input type="text" name="q" value="{{ search_query }}" class="search-query" placeholder="Search the App Store">
            </form>
          </li>
          {# User menu #}
          {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {{ user.get_full_name }} <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                {% if user.is_staff %}
                  <li><a href="/admin/">Admin Panel</a></li>
                  <li><a href="/backend/create/">Create a New App</a></li>
                {% endif %}
                <li><a href="/users/myapps">My Apps</a></li>
                <li><a href="/password-change">Change Password</a></li>
                <li><a href="{% url 'accounts:logout' %}">Sign out</a></li>
              </ul>
            </li>
          {% else %}
            <li {% ifequal navbar_selected 'signin' %}class="active"{% endifequal %}><a href="{% url 'accounts:login' %}">Sign In</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>

  <div class="container" style="padding-top: 4em;">
    {# Alert boxes at the top #}
    <div class="row"><div class="span6 offset3" id="cy-alerts"></div></div>
    <script src="{% get_static_prefix %}common/js/msgs.js"></script>

    {# Content #}
    {% block content %}{% endblock %}

    {# Footer #}
    <hr style="margin-top: 6em;">
    <footer style="text-align: center;">
      Site design courtesy of <a href="http://www.cytoscape.org">Cytoscape project</a>
    </footer>
  </div>

  {# Check browser version #}
  <script type="text/javascript" src="{% get_static_prefix %}common/js/check_browser_version.js"></script>

  {# Support for "Go back to..." links at the top #}
  <script type="text/javascript">
    $(window).on('pageshow', function() {
      {% if go_back_to %}
        $.cookie('go_back_to_title', '{{ go_back_to }}',  {'path': '/'});
        $.cookie('go_back_to_url',   '{{ request.get_full_path }}', {'path': '/'});
      {% endif %}
    });
  </script>
</body>
</html>

src/templates/base2.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    {% block more_head %}
    {% endblock %}
  </head>


  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>

                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}

    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <hr style="margin-top: 6em;">
      <footer style="text-align: center;">
        Site design courtesy of <a href="http://www.cytoscape.org">Cytoscape project</a>
      </footer>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% comment %} <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> {% endcomment %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "nav_panel.html" %}
{% load app_buttons %}

{% block main %}
  <style type="text/css">
    h2 { margin-bottom: 0.5em; }
    .span4 { margin-bottom: 1em; }
  </style>
  <div class="row">
    <div class="span4"><h2>Newest Releases</h2></div>
    <div class="span4" style="text-align: right; margin-top: 1.0em;">
      <a href="https://www.nsnam.org/docs/app-store-overview.pdf" class="btn btn-warning">Get Started with the App Store &raquo;</a>
    </div>
  </div>
  <div class="row">{% app_buttons new_releases %}</div>
  <div class="row">
    <div class="span8" style="text-align: right;">
      <a href="/app/tag/all/#newest release">more newest releases &raquo;</a>
    </div>
  </div>
  <a style="display: none;" href="/media/fu.txt">fu skript kiddiez</a>
{% endblock %}

src/templates/nav_panel.html
{% extends "base.html" %}
{% load static %}

{% block more_head %}
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/nav_panel.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_button.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css"/>
  <style type="text/css">
    .icon-cy-tag-cloud {
      background-image: url("{% get_static_prefix %}apps/img/tag_cloud.png");
    }
  </style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="span4" id="cy-nav-panel">
    <div class="well">
      <div id="title">
        <table width="100%">
          <tr>
            <td>
              <h4 style="margin: 0">
                {% ifequal navbar_selected_link "all" %}
                  All Apps
                {% else %}
                  <a href="/app/tag/all/">All Apps</a>
                {% endifequal %}
              </h4>
            </td>
          </tr>
          <tr>
            <td><h3>Categories</h3></td>
            <td>
              <div class="pull-right">
                <div id="cy-tag-buttons" class="btn-group">
                  <button class="btn btn-mini" id="cy-tag-list-btn"><i class="icon-align-left"></i></button>
                  <button class="btn btn-mini" id="cy-tag-cloud-btn"><i class="icon-cy-tag-cloud"></i></button>
                </div>
              </div>
            </td>
          </tr>
        </table>
      </div>

      <div id="cy-tag-list">
        <ul class="nav nav-list" id="top-tags">
          {% for tag in top_tags %}
            <li {% ifequal tag.name selected_tag_name %} class="active" {% endifequal %}>
            <a href="/app/tag/{{ tag.identity }}"><h5>
              <span class="title">{{ tag.name }}</span>
              <!--span class="count">({{ tag.count }})</span-->
            </h5></a></li>
          {% endfor %}
          <li class="divider"></li>
          <p><button class="btn btn-small" id="more-button"></button></p>
        </ul>
        <ul class="nav nav-list" id="not-top-tags">
          {% for tag in not_top_tags %}
            <li {% ifequal tag.name selected_tag_name %} class="active" {% endifequal %}>
            <a href="/app/tag/{{ tag.identity }}"><h5>
              <span class="title">{{ tag.name }}</span>
              <!--span class="count">({{ tag.count }})</span-->
            </h5></a></li>
          {% endfor %}
        </ul>
      </div>

      <div id="cy-tag-cloud">
        {% for tag in all_tags %}
        <a {% ifequal tag.name selected_tag_name %} class="cy-tag-cloud-active" {% endifequal %} style="font-size: {{ tag.font_size_em }}em" href="/app/tag/{{ tag.id }}">{{tag.name}}</a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="span8">
    {% block main %}{% endblock %}
  </div>
</div>

<script type="text/javascript" src="{% get_static_prefix %}apps/js/nav_panel.js"></script>
{% endblock %}