src/apps/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'apps'

urlpatterns = [
	# This URL can be used to make use of SearchFilterForm and filter 
	# search results based on User inputs. Refer forms.py and uncomment this when required.
    # path('tag/', views.tagSearch, name='tagSearch'),
    path('<slug:name>/', views.appPage, name='appPage'),
    path('tag/all/', views.tagSearch, name='allApps'),
    path('tag/<slug:name>/', views.tagSearch, name='tagSearch'),
    path('feedback/<int:num>/', views.feedback, name='feedback'),
]

src/download/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'download'

urlpatterns = [
    path(
        'stats/',
        views.all_stats,
        name='all_stats'),
    path(
        'stats/<slug:name>',
        views.app_stats,
        name='app_stats'),
]

src/download/models.py
from django.db import models
from apps.models import App, Release
from util.views import ipaddr_long_to_str


class Download(models.Model):
    release = models.ForeignKey(Release, related_name='app_download_stats', on_delete=models.CASCADE)
    when = models.DateField()
    ip4addr = models.PositiveIntegerField()

    def __unicode__(self):
        return unicode(self.release) + u' ' + unicode(self.when) + u' ' + ipaddr_long_to_str(self.ip4addr)


class ReleaseDownloadsByDate(models.Model):
    release = models.ForeignKey(Release, null = True, on_delete=models.CASCADE) # null release has total count across a given day
    when = models.DateField()
    count = models.PositiveIntegerField(default = 0)

    def __unicode__(self):
        return unicode(self.release) + u' ' + unicode(self.when) + u': ' + unicode(self.count)

src/download/views.py
from django.shortcuts import render, get_object_or_404
from apps.models import App
from download.models import ReleaseDownloadsByDate

def all_stats(request):
    apps = App.objects.filter(active=True)
    context = {
            'apps': apps,
    }
    return render(request, 'all_stats.html', context)


def app_stats(request, name):
    app = get_object_or_404(App, active = True, name = name)
    releases = app.release_set.all()
    app_timeline = dict()
    for r in releases:
        temp = ReleaseDownloadsByDate.objects.filter(release=r).order_by('-when')
        for t in temp:
            app_timeline[t.when] = {}
    
    for r in releases:
        temp = ReleaseDownloadsByDate.objects.filter(release=r)
        for t in temp:
            for re in releases:
                app_timeline[t.when][re.version]=0

    for r in releases:
        temp = ReleaseDownloadsByDate.objects.filter(release=r)
        for t in temp:
            app_timeline[t.when][t.release.version] = 0
            app_timeline[t.when][t.release.version] += t.count

    context = {
            'app': app,
            'app_timeline': app_timeline,
            'releases': releases
    }
    return render(request, 'app_stats.html', context)

src/download/templates/all_stats.html
{% extends "base.html" %}
{% load static %}

{% block more_head %}
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_page.css" />
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css" />
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/jquery.timeago.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Converter.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/setup_ajax_for_csrf.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/markdown_util.js"></script>
{% endblock %}

{% block title %} - {{ app.title }} - Download Statistics{% endblock %}

{% block content %}
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>
        All App Stats
        <small>Download Statistics</small>
      </h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12">
     <table class="table table-hover table-striped table-bordered">
     	<thead>
     		<th>App Name</th>
     		<th>Total Downloads</th>
     		<th>Action</th>
     	</thead>
     	<tbody>
     		{% for app in apps %}
     		<tr>
     			<td>{{ app.title }}</td>
     			<td>{{ app.downloads }}</td>
     			<td><a href="{% url 'download:app_stats' app.name %}" target="_blank">View detailed stats</a></td>
     		</tr>
     		{% endfor %}
     	</tbody>
     </table>
  </div>
</div>
{% endblock %}

src/download/templates/app_stats.html
{% extends "base.html" %}
{% load static %}

{% block more_head %}
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_page.css" />
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css" />
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/jquery.timeago.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Converter.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/setup_ajax_for_csrf.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/markdown_util.js"></script>
{% endblock %}

{% block title %} - {{ app.title }} - Download Statistics{% endblock %}

{% block content %}
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>
        {{ app.title }}
        <small>Download Statistics</small>
      </h1>
      <h3>Total downloads: {{ app.downloads }}</h3>
    </div>
  </div>
</div>

{% if app.downloads > 0 %}
<div class="row">
  <div class="span12">
     <table class="table table-hover table-striped table-bordered">
        <thead>
            <th>Date</th>
            {% for release in releases %}
            <th>
                {{ release.version }}
            </th>
            {% endfor %}
        </thead>
        <tbody>
            {% for date, releases in app_timeline.items %}
            <tr>
                <td>{{ date }}</td>
                {% for release, count in releases.items %}
                    <td>{{ count }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
     	</tbody>
     </table>
  </div>
</div>
{% endif %}
{% endblock %}